import { mkdirSync, writeFileSync } from "fs";
import { resolve } from "path";
import { execSync } from "child_process";

const WORKSPACES_DIR = resolve(import.meta.dirname, "../../workspaces");

export function initLocalRepo(taskId: string): { workspacePath: string } {
  const workspacePath = resolve(WORKSPACES_DIR, taskId);
  mkdirSync(workspacePath, { recursive: true });

  writeFileSync(
    resolve(workspacePath, "README.md"),
    `# ${taskId}\n\nGenerated by the Software Factory (local mode).\n`
  );

  execSync("git init", { cwd: workspacePath, stdio: "pipe" });
  execSync("git add -A", { cwd: workspacePath, stdio: "pipe" });
  execSync('git commit -m "Initial commit"', {
    cwd: workspacePath,
    stdio: "pipe",
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: "Factory",
      GIT_AUTHOR_EMAIL: "factory@local",
      GIT_COMMITTER_NAME: "Factory",
      GIT_COMMITTER_EMAIL: "factory@local",
    },
  });

  console.log(`[local-repo] Initialized workspace: ${workspacePath}`);
  return { workspacePath };
}
